### ISSUE TITLE
Can you make shipping address and billing address optional

### ISSUE THREAD

**Issue by limesquare-nl** [andypieters/omnipay-paynl#22]
In the PurchaseRequest can you check if billing and shipping address is filled. Now it gives me a error. I'm making a digital purchase that's not being shipped.

**Comment by andypieters** [comment]
Yes, i'll put it on my todo.
Ill also update the tests for this.

**Comment by andypieters** [comment]
Can you please tell me what error you are getting?
I've just added some tests for this, but iam not getting an error.
https://github.com/andypieters/omnipay-paynl/blob/master/tests/Message/PurchaseRequestTest.php#L49-L96
