### ISSUE TITLE
API version 12

### ISSUE THREAD

**Issue by sashaskr** [andypieters/omnipay-paynl#25]
https://github.com/andypieters/omnipay-paynl/blob/76865a7a98f381b8b770889d4d027879147b6701/src/Message/AbstractRequest.php#L8
Hey @andypieters,
Does it have v12 support API calls?

**Comment by andypieters** [comment]
At the moment all requests will work, except for the refund.
The response of the refund api is different, so i'll have to write a workaround for that

**Comment by sashaskr** [comment]
Thank you @andypieters for your reply. I was interested based on conversation here: https://github.com/paynl/sdk/issues/54, because of refund api response might be different.
